In [ ]:
#KFold Validation 
#XGBoost

#OOPs 
#REgex
#Time Series
#Reinforcement
#Discuss about use cases whic hwe can create from your day to day data

In [1]:
import os 
os.chdir('D:\\Edureka\\Jun 1 - Edureka - Python\\Class 12 - Codes\\')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [7]:
dataset

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
5    15728773    Male  27.0          58000.0          0
6    15598044  Female  27.0          84000.0          0
7    15694829  Female  32.0         150000.0          1
8    15600575    Male  25.0          33000.0          0
9    15727311  Female  35.0          65000.0          0
10   15570769  Female  26.0          80000.0          0
11   15606274  Female  26.0          52000.0          0
12   15746139    Male  20.0          86000.0          0
13   15704987    Male  32.0          18000.0          0
14   15628972    Male  18.0          82000.0          0
15   15697686    Male  29.0          80000.0          0
16   15733883    Male  47.0          25000.0          1
17   15617482    Male  45.0          26000.0          1
18   15704583    Male  46.0          28000.0          1
19   15621083  Female  48.0          29000.0          1
20   15649487    Male  45.0          22000.0          1
21   15736760  Female  47.0          49000.0          1
22   15714658    Male  48.0          41000.0          1
23   15599081  Female  45.0          22000.0          1
24   15705113    Male  46.0          23000.0          1
25   15631159    Male  47.0          20000.0          1
26   15792818    Male  49.0          28000.0          1
27   15633531  Female  47.0          30000.0          1
28   15744529    Male  29.0          43000.0          0
29   15669656    Male  31.0          18000.0          0
..        ...     ...   ...              ...        ...
370  15611430  Female  60.0          46000.0          1
371  15774744    Male  60.0          83000.0          1
372  15629885  Female  39.0          73000.0          0
373  15708791    Male  59.0         130000.0          1
374  15793890  Female  37.0          80000.0          0
375  15646091  Female  46.0          32000.0          1
376  15596984  Female  46.0          74000.0          0
377  15800215  Female  42.0          53000.0          0
378  15577806    Male  41.0          87000.0          1
379  15749381  Female  58.0          23000.0          1
380  15683758    Male  42.0          64000.0          0
381  15670615    Male  48.0          33000.0          1
382  15715622  Female  44.0         139000.0          1
383  15707634    Male  49.0          28000.0          1
384  15806901  Female  57.0          33000.0          1
385  15775335    Male  56.0          60000.0          1
386  15724150  Female  49.0          39000.0          1
387  15627220    Male  39.0          71000.0          0
388  15672330    Male  47.0          34000.0          1
389  15668521  Female  48.0          35000.0          1
390  15807837    Male  48.0          33000.0          1
391  15592570    Male  47.0          23000.0          1
392  15748589  Female  45.0          45000.0          1
393  15635893    Male  60.0          42000.0          1
394  15757632  Female  39.0          59000.0          0
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [8]:
x = dataset.iloc[:, [2,3]].values

In [10]:
pd.DataFrame(x)

        0         1
0    19.0   19000.0
1    35.0   20000.0
2    26.0   43000.0
3    27.0   57000.0
4    19.0   76000.0
5    27.0   58000.0
6    27.0   84000.0
7    32.0  150000.0
8    25.0   33000.0
9    35.0   65000.0
10   26.0   80000.0
11   26.0   52000.0
12   20.0   86000.0
13   32.0   18000.0
14   18.0   82000.0
15   29.0   80000.0
16   47.0   25000.0
17   45.0   26000.0
18   46.0   28000.0
19   48.0   29000.0
20   45.0   22000.0
21   47.0   49000.0
22   48.0   41000.0
23   45.0   22000.0
24   46.0   23000.0
25   47.0   20000.0
26   49.0   28000.0
27   47.0   30000.0
28   29.0   43000.0
29   31.0   18000.0
..    ...       ...
370  60.0   46000.0
371  60.0   83000.0
372  39.0   73000.0
373  59.0  130000.0
374  37.0   80000.0
375  46.0   32000.0
376  46.0   74000.0
377  42.0   53000.0
378  41.0   87000.0
379  58.0   23000.0
380  42.0   64000.0
381  48.0   33000.0
382  44.0  139000.0
383  49.0   28000.0
384  57.0   33000.0
385  56.0   60000.0
386  49.0   39000.0
387  39.0   71000.0
388  47.0   34000.0
389  48.0   35000.0
390  48.0   33000.0
391  47.0   23000.0
392  45.0   45000.0
393  60.0   42000.0
394  39.0   59000.0
395  46.0   41000.0
396  51.0   23000.0
397  50.0   20000.0
398  36.0   33000.0
399  49.0   36000.0

[400 rows x 2 columns]

In [11]:
y = dataset.iloc[:,4].values

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1], dtype=int64)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [17]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(x_train,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [18]:
y_pred = classifier.predict(x_test)

In [19]:
y_pred

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[60,  6],
       [ 2, 32]], dtype=int64)

In [21]:
len(x_train)

300

In [22]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.04145277051436831

In [31]:
accuracies.mean()

0.9067593622543567

In [32]:
len(x_test)

100

In [30]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = x_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.04145277051436831

In [28]:
accuracies.mean()

0.9091919191919192