In [1]:
import os
os.chdir('D:\\Edureka\\08APR - 2019 - Python\\Misc\\PCA\\')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('Bank-data.csv')

In [4]:
dataset

     Index  interest_rate  credit  Gender  previous  duration Churn
0        0          1.334       0       1         0       117    no
1        1          0.767       0       0         1       274   yes
2        2          4.858       0       1         0       167    no
3        3          4.120       0       0         0       686   yes
4        4          4.856       0       1         0       159    no
5        5          0.899       0       0         0       120    no
6        6          4.962       0       0         0       337    no
7        7          4.858       0       1         0       640    no
8        8          4.962       0       0         0       663   yes
9        9          4.865       0       0         0       403    no
10      10          1.365       0       0         1       300    no
11      11          4.962       0       0         0       255   yes
12      12          4.858       0       0         1       293   yes
13      13          4.962       0       0         0        68    no
14      14          4.865       0       0         0       266    no
15      15          1.334       0       0         0       266   yes
16      16          0.767       0       0         1       159   yes
17      17          4.858       1       1         0       120   yes
18      18          4.120       0       1         0       337   yes
19      19          4.856       0       0         0       640    no
20      20          0.899       0       0         0       663   yes
21      21          4.962       0       0         1       403   yes
22      22          4.858       0       1         0       300    no
23      23          4.962       0       0         0       255   yes
24      24          4.865       0       1         1       293   yes
25      25          1.365       0       1         0        68    no
26      26          4.962       0       0         0       266   yes
27      27          4.858       0       0         0       272   yes
28      28          4.962       0       0         0       398   yes
29      29          4.865       0       0         0       126    no
..     ...            ...     ...     ...       ...       ...   ...
488    488          0.885       0       0         1       608   yes
489    489          4.153       0       0         0       250    no
490    490          0.735       0       0         0       107   yes
491    491          4.965       0       0         0       716   yes
492    492          4.859       0       1         0       619   yes
493    493          4.864       0       0         0       406    no
494    494          4.963       0       0         0        73    no
495    495          1.334       0       1         0       127    no
496    496          4.153       0       0         0       187    no
497    497          0.646       1       0         1       180   yes
498    498          1.266       0       1         0       326   yes
499    499          1.405       0       0         0       109   yes
500    500          0.900       0       0         1       470   yes
501    501          4.076       0       0         0        73    no
502    502          1.050       0       0         0       141    no
503    503          1.029       0       0         0       115    no
504    504          0.748       0       0         1       171    no
505    505          4.961       0       0         0       498    no
506    506          1.268       0       0         0       365   yes
507    507          4.959       0       0         0        10    no
508    508          4.021       0       0         0       796   yes
509    509          0.877       0       0         1       279   yes
510    510          1.327       0       1         0       476   yes
511    511          4.965       0       0         0       479   yes
512    512          1.266       0       1         0       225    no
513    513          1.334       0       1         0       204    no
514    514          0.861       0       0         1       806   yes
515    515          0.879       0       0         0       290    no
516    516          0.877       0       0         1       473   yes
517    517          4.965       0       0         0       142    no

[518 rows x 7 columns]

In [5]:
dataset['Churn'] = dataset['Churn'].astype('category')

In [6]:
dataset['Churn'] = dataset['Churn'].cat.codes

In [7]:
dataset

     Index  interest_rate  credit  Gender  previous  duration  Churn
0        0          1.334       0       1         0       117      0
1        1          0.767       0       0         1       274      1
2        2          4.858       0       1         0       167      0
3        3          4.120       0       0         0       686      1
4        4          4.856       0       1         0       159      0
5        5          0.899       0       0         0       120      0
6        6          4.962       0       0         0       337      0
7        7          4.858       0       1         0       640      0
8        8          4.962       0       0         0       663      1
9        9          4.865       0       0         0       403      0
10      10          1.365       0       0         1       300      0
11      11          4.962       0       0         0       255      1
12      12          4.858       0       0         1       293      1
13      13          4.962       0       0         0        68      0
14      14          4.865       0       0         0       266      0
15      15          1.334       0       0         0       266      1
16      16          0.767       0       0         1       159      1
17      17          4.858       1       1         0       120      1
18      18          4.120       0       1         0       337      1
19      19          4.856       0       0         0       640      0
20      20          0.899       0       0         0       663      1
21      21          4.962       0       0         1       403      1
22      22          4.858       0       1         0       300      0
23      23          4.962       0       0         0       255      1
24      24          4.865       0       1         1       293      1
25      25          1.365       0       1         0        68      0
26      26          4.962       0       0         0       266      1
27      27          4.858       0       0         0       272      1
28      28          4.962       0       0         0       398      1
29      29          4.865       0       0         0       126      0
..     ...            ...     ...     ...       ...       ...    ...
488    488          0.885       0       0         1       608      1
489    489          4.153       0       0         0       250      0
490    490          0.735       0       0         0       107      1
491    491          4.965       0       0         0       716      1
492    492          4.859       0       1         0       619      1
493    493          4.864       0       0         0       406      0
494    494          4.963       0       0         0        73      0
495    495          1.334       0       1         0       127      0
496    496          4.153       0       0         0       187      0
497    497          0.646       1       0         1       180      1
498    498          1.266       0       1         0       326      1
499    499          1.405       0       0         0       109      1
500    500          0.900       0       0         1       470      1
501    501          4.076       0       0         0        73      0
502    502          1.050       0       0         0       141      0
503    503          1.029       0       0         0       115      0
504    504          0.748       0       0         1       171      0
505    505          4.961       0       0         0       498      0
506    506          1.268       0       0         0       365      1
507    507          4.959       0       0         0        10      0
508    508          4.021       0       0         0       796      1
509    509          0.877       0       0         1       279      1
510    510          1.327       0       1         0       476      1
511    511          4.965       0       0         0       479      1
512    512          1.266       0       1         0       225      0
513    513          1.334       0       1         0       204      0
514    514          0.861       0       0         1       806      1
515    515          0.879       0       0         0       290      0
516    516          0.877       0       0         1       473      1
517    517          4.965       0       0         0       142      0

[518 rows x 7 columns]

In [10]:
x = dataset.iloc[:,0:6].values

In [12]:
y = dataset.iloc[:,6].values

In [13]:
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [15]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
y_pred = logmodel.predict(x_test)

In [30]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train_n, y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
y_pred = logmodel.predict(x_test_n)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#89.42%

array([[41,  9],
       [23, 31]], dtype=int64)

In [20]:
from sklearn.decomposition import PCA #Principal component analysis
pca = PCA(n_components=None)
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [28]:
from sklearn.decomposition import PCA #Principal component analysis
pca = PCA(n_components=2)
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [22]:
pd.DataFrame(x_train)

         0      1    2    3    4       5
0     63.0  0.715  0.0  0.0  0.0   254.0
1    326.0  1.270  0.0  1.0  0.0   322.0
2    117.0  1.313  0.0  1.0  0.0   728.0
3     30.0  4.965  0.0  0.0  0.0    35.0
4    363.0  1.281  0.0  1.0  0.0   149.0
5     88.0  0.883  0.0  0.0  0.0   254.0
6    248.0  4.957  0.0  0.0  0.0   873.0
7    362.0  1.410  0.0  0.0  0.0   198.0
8     20.0  0.899  0.0  0.0  0.0   663.0
9    164.0  0.879  0.0  0.0  0.0   173.0
10   104.0  4.021  0.0  0.0  0.0   331.0
11   355.0  4.968  0.0  0.0  0.0   188.0
12   265.0  4.961  0.0  0.0  0.0   135.0
13    73.0  0.635  1.0  0.0  0.0   238.0
14   365.0  4.962  0.0  0.0  0.0  1009.0
15   333.0  0.904  0.0  0.0  1.0   203.0
16   387.0  1.048  0.0  0.0  0.0    74.0
17   259.0  4.966  0.0  0.0  0.0   396.0
18   470.0  1.049  0.0  0.0  1.0   482.0
19   342.0  1.498  0.0  0.0  0.0  1176.0
20   111.0  1.405  0.0  0.0  0.0   113.0
21   201.0  4.960  0.0  0.0  0.0   617.0
22   463.0  4.076  0.0  0.0  0.0   151.0
23   352.0  4.858  0.0  1.0  0.0    58.0
24   361.0  4.966  0.0  0.0  0.0   116.0
25   258.0  0.879  0.0  0.0  0.0   363.0
26   206.0  1.799  1.0  0.0  0.0   320.0
27   199.0  1.260  0.0  0.0  0.0   269.0
28    52.0  4.964  0.0  0.0  0.0    87.0
29   146.0  1.250  0.0  1.0  0.0   239.0
..     ...    ...  ...  ...  ...     ...
384  158.0  1.344  0.0  1.0  1.0   632.0
385  316.0  4.963  0.0  0.0  0.0   988.0
386  406.0  4.864  0.0  0.0  0.0   357.0
387  484.0  1.365  0.0  0.0  0.0  1143.0
388  391.0  1.291  0.0  1.0  0.0    59.0
389  492.0  4.859  0.0  1.0  0.0   619.0
390   98.0  4.962  0.0  0.0  0.0  1130.0
391  309.0  1.266  0.0  0.0  1.0   174.0
392  183.0  4.966  0.0  0.0  0.0   809.0
393   79.0  4.961  0.0  0.0  0.0    70.0
394  122.0  0.977  0.0  0.0  1.0   252.0
395  186.0  4.857  0.0  1.0  0.0    16.0
396  499.0  1.405  0.0  0.0  0.0   109.0
397   69.0  4.120  0.0  0.0  0.0   104.0
398  413.0  4.967  0.0  0.0  0.0   455.0
399  411.0  1.259  0.0  1.0  1.0   582.0
400  447.0  4.856  0.0  1.0  0.0   446.0
401   13.0  4.962  0.0  0.0  0.0    68.0
402  115.0  4.960  0.0  0.0  0.0    35.0
403  281.0  1.327  0.0  1.0  0.0   143.0
404  157.0  1.334  0.0  1.0  0.0   984.0
405  239.0  1.028  0.0  0.0  0.0   383.0
406  382.0  4.963  0.0  0.0  0.0   183.0
407  210.0  0.898  0.0  0.0  0.0   209.0
408  405.0  4.857  0.0  1.0  0.0   159.0
409  278.0  4.856  0.0  1.0  0.0   273.0
410   87.0  0.773  0.0  0.0  0.0   355.0
411   45.0  0.739  0.0  0.0  0.0   115.0
412  425.0  4.021  0.0  0.0  0.0   248.0
413  225.0  4.857  0.0  1.0  0.0   211.0

[414 rows x 6 columns]

In [29]:
pd.DataFrame(x_train_n)

              0           1
0   -128.800927  195.358859
1    -54.768709  -66.007096
2    346.315864  152.277491
3   -348.502671  223.312749
4   -226.871753 -106.977110
5   -128.225832  170.365501
6    494.290566   24.648359
7   -177.907804 -104.850162
8    279.101607  247.756416
9   -207.456041   92.522237
10   -50.878542  156.141573
11  -188.066651  -98.081519
12  -243.123042   -9.324588
13  -144.566641  184.993511
14   632.946117  -89.192039
15  -173.576214  -75.743004
16  -301.299824 -132.696180
17    17.669855    2.678044
18   108.501567 -206.288420
19   799.373261  -62.356874
20  -268.659477  144.128009
21   237.277098   65.746724
22  -222.572240 -206.904244
23  -318.101184  -98.072901
24  -259.909567 -105.736268
25   -15.343887    2.918003
26   -59.528874   53.915271
27  -110.676334   59.740006
28  -296.010330  202.514815
29  -141.887578  112.035873
..          ...         ...
384  251.284440  109.079786
385  610.824447  -40.688106
386  -17.938126 -145.180248
387  769.648673 -205.078466
388 -316.203806 -137.040118
389  245.970998 -225.130228
390  747.771851  180.520860
391 -203.120697  -52.416437
392  428.812200   88.158858
393 -312.384705  175.130881
394 -129.443173  136.328391
395 -363.908841   66.916968
396 -263.732612 -243.861319
397 -278.623641  185.910265
398   80.196957 -149.923922
399  207.117862 -145.003500
400   71.981573 -184.121946
401 -315.902483  241.067404
402 -346.547275  138.335245
403 -234.756553  -25.136833
404  603.168296  118.177277
405    4.213712   22.373090
406 -192.444201 -125.189398
407 -170.407357   47.362582
408 -215.908667 -148.735403
409 -104.860428  -19.146483
410  -27.275552  173.688691
411 -268.178227  210.156449
412 -126.472081 -166.682857
413 -168.063267   32.413201

[414 rows x 2 columns]

In [25]:
explained_variance = pca.explained_variance_ratio_

In [33]:
pd.DataFrame(explained_variance)

              0
0  8.644575e-01
1  1.355193e-01
2  2.137104e-05
3  1.240383e-06
4  4.712005e-07
5  1.727750e-07